import { SIGN_UP, LOG_IN } from './auth';
import { GET_USERS, GET_USER, CREATE_USER, UPDATE_USER, DELETE_USER } from './employees';
import { GET_SELECT_LISTS } from './selectLists';
import { GET_PROJECTS, GET_PROJECT, UPDATE_PROJECT, CREATE_PROJECT, DELETE_PROJECT } from './projects';
import { GET_CVS, DELETE_CV } from './cvs';

export {
  SIGN_UP,
  LOG_IN,
  GET_USERS,
  GET_USER,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
  GET_SELECT_LISTS,
  GET_PROJECTS,
  UPDATE_PROJECT,
  CREATE_PROJECT,
  DELETE_PROJECT,
  GET_PROJECT,
  GET_CVS,
  DELETE_CV,
};
